In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/heart_statlog_cleveland_hungary_final.csv")

1. Check Missing values
2. Check Duplicates
3. Check data type
4. Check the number of unique values of each column
5. Check statistics of data set
6. Check various categories present in the different categorical column

In [ ]:
df.head()

age  sex  chest pain type  resting bp s  cholesterol  fasting blood sugar  \
0   40    1                2           140          289                    0   
1   49    0                3           160          180                    0   
2   37    1                2           130          283                    0   
3   48    0                4           138          214                    0   
4   54    1                3           150          195                    0   

   resting ecg  max heart rate  exercise angina  oldpeak  ST slope  target  
0            0             172                0      0.0         1       0  
1            0             156                0      1.0         2       1  
2            1              98                0      0.0         1       0  
3            0             108                1      1.5         2       1  
4            0             122                0      0.0         1       0

In [ ]:
df.isnull().sum()

age                    0
sex                    0
chest pain type        0
resting bp s           0
cholesterol            0
fasting blood sugar    0
resting ecg            0
max heart rate         0
exercise angina        0
oldpeak                0
ST slope               0
target                 0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1190 entries, 0 to 1189
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   age                  1190 non-null   int64  
 1   sex                  1190 non-null   int64  
 2   chest pain type      1190 non-null   int64  
 3   resting bp s         1190 non-null   int64  
 4   cholesterol          1190 non-null   int64  
 5   fasting blood sugar  1190 non-null   int64  
 6   resting ecg          1190 non-null   int64  
 7   max heart rate       1190 non-null   int64  
 8   exercise angina      1190 non-null   int64  
 9   oldpeak              1190 non-null   float64
 10  ST slope             1190 non-null   int64  
 11  target               1190 non-null   int64  
dtypes: float64(1), int64(11)
memory usage: 111.7 KB


In [ ]:
df.describe()

age          sex  chest pain type  resting bp s  cholesterol  \
count  1190.000000  1190.000000      1190.000000   1190.000000  1190.000000   
mean     53.720168     0.763866         3.232773    132.153782   210.363866   
std       9.358203     0.424884         0.935480     18.368823   101.420489   
min      28.000000     0.000000         1.000000      0.000000     0.000000   
25%      47.000000     1.000000         3.000000    120.000000   188.000000   
50%      54.000000     1.000000         4.000000    130.000000   229.000000   
75%      60.000000     1.000000         4.000000    140.000000   269.750000   
max      77.000000     1.000000         4.000000    200.000000   603.000000   

       fasting blood sugar  resting ecg  max heart rate  exercise angina  \
count          1190.000000  1190.000000     1190.000000      1190.000000   
mean              0.213445     0.698319      139.732773         0.387395   
std               0.409912     0.870359       25.517636         0.487360   
min               0.000000     0.000000       60.000000         0.000000   
25%               0.000000     0.000000      121.000000         0.000000   
50%               0.000000     0.000000      140.500000         0.000000   
75%               0.000000     2.000000      160.000000         1.000000   
max               1.000000     2.000000      202.000000         1.000000   

           oldpeak     ST slope       target  
count  1190.000000  1190.000000  1190.000000  
mean      0.922773     1.624370     0.528571  
std       1.086337     0.610459     0.499393  
min      -2.600000     0.000000     0.000000  
25%       0.000000     1.000000     0.000000  
50%       0.600000     2.000000     1.000000  
75%       1.600000     2.000000     1.000000  
max       6.200000     3.000000     1.000000

In [ ]:
df.duplicated().sum()

272

In [ ]:
df = df.drop_duplicates()


In [ ]:
df.shape

(918, 12)

In [ ]:
df

age  sex  chest pain type  resting bp s  cholesterol  \
0      40    1                2           140          289   
1      49    0                3           160          180   
2      37    1                2           130          283   
3      48    0                4           138          214   
4      54    1                3           150          195   
...   ...  ...              ...           ...          ...   
1185   45    1                1           110          264   
1186   68    1                4           144          193   
1187   57    1                4           130          131   
1188   57    0                2           130          236   
1189   38    1                3           138          175   

      fasting blood sugar  resting ecg  max heart rate  exercise angina  \
0                       0            0             172                0   
1                       0            0             156                0   
2                       0            1              98                0   
3                       0            0             108                1   
4                       0            0             122                0   
...                   ...          ...             ...              ...   
1185                    0            0             132                0   
1186                    1            0             141                0   
1187                    0            0             115                1   
1188                    0            2             174                0   
1189                    0            0             173                0   

      oldpeak  ST slope  target  
0         0.0         1       0  
1         1.0         2       1  
2         0.0         1       0  
3         1.5         2       1  
4         0.0         1       0  
...       ...       ...     ...  
1185      1.2         2       1  
1186      3.4         2       1  
1187      1.2         2       1  
1188      0.0         2       1  
1189      0.0         1       0  

[918 rows x 12 columns]

In [ ]:
df['chest pain type'].unique()

array([2, 3, 4, 1])

In [ ]:
df['fasting blood sugar'].unique()

array([0, 1])

In [ ]:
df['resting ecg'].unique()

array([0, 1, 2])

In [ ]:
df['cholesterol'].min()

0

In [ ]:
df['cholesterol'].max()

603

In [ ]:
df['resting bp s'].min()

0

In [ ]:
df['resting bp s'].max()

200

In [ ]:
from sklearn.preprocessing import MinMaxScaler


In [ ]:
df['cholesterol']

0       289
1       180
2       283
3       214
4       195
       ... 
1185    264
1186    193
1187    131
1188    236
1189    175
Name: cholesterol, Length: 918, dtype: int64

In [ ]:
scaler = MinMaxScaler()
df['cholesterol']=scaler.fit_transform(df[['cholesterol']])
df['resting bp s']=scaler.fit_transform(df[['resting bp s']])
df['max heart rate']=scaler.fit_transform(df[['max heart rate']])

In [ ]:
df

age  sex  chest pain type  resting bp s  cholesterol  \
0      40    1                2          0.70     0.479270   
1      49    0                3          0.80     0.298507   
2      37    1                2          0.65     0.469320   
3      48    0                4          0.69     0.354892   
4      54    1                3          0.75     0.323383   
...   ...  ...              ...           ...          ...   
1185   45    1                1          0.55     0.437811   
1186   68    1                4          0.72     0.320066   
1187   57    1                4          0.65     0.217247   
1188   57    0                2          0.65     0.391376   
1189   38    1                3          0.69     0.290216   

      fasting blood sugar  resting ecg  max heart rate  exercise angina  \
0                       0            0        0.788732                0   
1                       0            0        0.676056                0   
2                       0            1        0.267606                0   
3                       0            0        0.338028                1   
4                       0            0        0.436620                0   
...                   ...          ...             ...              ...   
1185                    0            0        0.507042                0   
1186                    1            0        0.570423                0   
1187                    0            0        0.387324                1   
1188                    0            2        0.802817                0   
1189                    0            0        0.795775                0   

      oldpeak  ST slope  target  
0         0.0         1       0  
1         1.0         2       1  
2         0.0         1       0  
3         1.5         2       1  
4         0.0         1       0  
...       ...       ...     ...  
1185      1.2         2       1  
1186      3.4         2       1  
1187      1.2         2       1  
1188      0.0         2       1  
1189      0.0         1       0  

[918 rows x 12 columns]

In [ ]:
df['age'].max()

77

In [ ]:
df['age'].min()

28